dist: trusty
sudo: required
os:
  - linux
language: python
python:
  - 2.7

env:
  global:
    - CC_TEST_REPORTER_ID=your_test_reporter_id_goes_here

branches:
  only:
  - master
  - /^(?!wip-).+$/

cache:
  pip: true
  directories:
  - $HOME/virtualenv/python2.7.13/lib/python2.7/site-packages
  - $HOME/virtualenv/python2.7.13/bin/

install:
  - scripts/travis_install.sh

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - scripts/travis_test.sh

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
